// <auto-generated />
using System;
using HRM.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRM.DAL.Migrations
{
    [DbContext(typeof(HrmDbContext))]
    [Migration("20260421121936_RemoveHieuSuatRankingAndUiFields")]
    partial class RemoveHieuSuatRankingAndUiFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRM.Domain.Entities.BangLuong", b =>
                {
                    b.Property<int>("MaBangLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBangLuong"));

                    b.Property<decimal>("BHTN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BHXH")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BHYT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LuongThucNhan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTinhLuong")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoGioLamThem")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SoNgayLamViec")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("ThueTNCN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienLamThem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongKhauTru")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongPhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongPhuCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongThuNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chờ duyệt");

                    b.HasKey("MaBangLuong");

                    b.HasIndex("Thang", "Nam");

                    b.HasIndex("MaNhanVien", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("BangLuong", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChamCong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GioLamThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("time");

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongGioLam")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Bình thường");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NgayChamCong");

                    b.HasIndex("MaNhanVien", "NgayChamCong")
                        .IsUnique();

                    b.ToTable("ChamCong", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChinhSach", b =>
                {
                    b.Property<int>("MaChinhSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChinhSach"));

                    b.Property<string>("LoaiChinhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiPheDuyet")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiPheDuyetNavMaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhamViApDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhienBan")
                        .HasColumnType("int");

                    b.Property<string>("TenChinhSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChinhSach");

                    b.HasIndex("NguoiPheDuyetNavMaNhanVien");

                    b.ToTable("ChinhSach", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<int>("CapBac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu", (string)null);

                    b.HasData(
                        new
                        {
                            MaChucVu = 1,
                            CapBac = 6,
                            MoTa = "Giám đốc điều hành công ty",
                            TenChucVu = "Giám đốc"
                        },
                        new
                        {
                            MaChucVu = 2,
                            CapBac = 5,
                            MoTa = "Phó Giám đốc",
                            TenChucVu = "Phó Giám đốc"
                        },
                        new
                        {
                            MaChucVu = 3,
                            CapBac = 4,
                            MoTa = "Trưởng phòng ban",
                            TenChucVu = "Trưởng phòng"
                        },
                        new
                        {
                            MaChucVu = 4,
                            CapBac = 3,
                            MoTa = "Phó phòng ban",
                            TenChucVu = "Phó phòng"
                        },
                        new
                        {
                            MaChucVu = 5,
                            CapBac = 2,
                            MoTa = "Trưởng nhóm làm việc",
                            TenChucVu = "Trưởng nhóm"
                        },
                        new
                        {
                            MaChucVu = 6,
                            CapBac = 1,
                            MoTa = "Nhân viên",
                            TenChucVu = "Nhân viên"
                        });
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChungChi", b =>
                {
                    b.Property<int>("MaChungChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChungChi"));

                    b.Property<string>("DuongDanFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiChungChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChungChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ToChucCap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaChungChi");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NgayHetHan");

                    b.ToTable("ChungChi", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChuongTrinhDaoTao", b =>
                {
                    b.Property<int>("MaDaoTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDaoTao"));

                    b.Property<decimal?>("ChiPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GiangVien")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MucTieu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoHocVienToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Lên kế hoạch");

                    b.HasKey("MaDaoTao");

                    b.ToTable("ChuongTrinhDaoTao", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.DanhGiaDaoTao", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int?>("ChatLuongKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("DanhGiaGiangVien")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("DiemSo")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaDaoTao")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhanHoiHocVien")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDaoTao");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DanhGiaDaoTao", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.DieuChinhChamCong", b =>
                {
                    b.Property<int>("MaDieuChinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDieuChinh"));

                    b.Property<TimeSpan?>("GioRaCu")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioRaMoi")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioVaoCu")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioVaoMoi")
                        .HasColumnType("time");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaChamCong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDieuChinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDieuChinh")
                        .HasColumnType("int");

                    b.HasKey("MaDieuChinh");

                    b.HasIndex("MaChamCong");

                    b.HasIndex("NguoiDieuChinh");

                    b.ToTable("DieuChinhChamCong", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.DonNghiPhep", b =>
                {
                    b.Property<int>("MaDonPhep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonPhep"));

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaLoaiPhep")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayPheDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiPheDuyet")
                        .HasColumnType("int");

                    b.Property<decimal>("SoNgayNghi")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chờ duyệt");

                    b.HasKey("MaDonPhep");

                    b.HasIndex("MaLoaiPhep");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NguoiPheDuyet");

                    b.HasIndex("TrangThai");

                    b.ToTable("DonNghiPhep", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.HieuSuatNhanVien", b =>
                {
                    b.Property<int>("MaHieuSuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHieuSuat"));

                    b.Property<decimal?>("DiemKPI")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("KetQuaCongViec")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaKyDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoGioLamViec")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("TyLeHoanThanhDeadline")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MaHieuSuat");

                    b.HasIndex("MaKyDanhGia");

                    b.HasIndex("MaNhanVien", "MaKyDanhGia")
                        .IsUnique();

                    b.ToTable("HieuSuatNhanVien", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.KyDanhGia", b =>
                {
                    b.Property<int>("MaKyDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKyDanhGia"));

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKyDanhGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Mở");

                    b.HasKey("MaKyDanhGia");

                    b.ToTable("KyDanhGia", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.LichSuChinhSach", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("ChinhSachMaChinhSach")
                        .HasColumnType("int");

                    b.Property<string>("LyDoSuaDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChinhSach")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySuaDoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiSuaDoi")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiSuaDoiNavMaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungThayDoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PhienBanCu")
                        .HasColumnType("int");

                    b.Property<int?>("PhienBanMoi")
                        .HasColumnType("int");

                    b.HasKey("MaLichSu");

                    b.HasIndex("ChinhSachMaChinhSach");

                    b.HasIndex("NguoiSuaDoiNavMaNhanVien");

                    b.ToTable("LichSuChinhSach", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.LichSuDieuChuyen", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaChucVuCu")
                        .HasColumnType("int");

                    b.Property<int?>("MaChucVuMoi")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhongBanCu")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhongBanMoi")
                        .HasColumnType("int");

                    b.Property<decimal?>("MucLuongCu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MucLuongMoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayThayDoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiThucHien")
                        .HasColumnType("int");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaChucVuCu");

                    b.HasIndex("MaChucVuMoi");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhongBanCu");

                    b.HasIndex("MaPhongBanMoi");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("LichSuDieuChuyen", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.LoaiNghiPhep", b =>
                {
                    b.Property<int>("MaLoaiPhep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhep"));

                    b.Property<bool>("CoLuong")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TenLoaiPhep")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiPhep");

                    b.ToTable("LoaiNghiPhep", (string)null);

                    b.HasData(
                        new
                        {
                            MaLoaiPhep = 1,
                            CoLuong = true,
                            MoTa = "Nghỉ phép hàng năm theo quy định",
                            TenLoaiPhep = "Phép năm"
                        },
                        new
                        {
                            MaLoaiPhep = 2,
                            CoLuong = true,
                            MoTa = "Nghỉ ốm có giấy xác nhận y tế",
                            TenLoaiPhep = "Phép ốm"
                        },
                        new
                        {
                            MaLoaiPhep = 3,
                            CoLuong = false,
                            MoTa = "Nghỉ không hưởng lương",
                            TenLoaiPhep = "Phép không lương"
                        },
                        new
                        {
                            MaLoaiPhep = 4,
                            CoLuong = true,
                            MoTa = "Nghỉ do việc cá nhân",
                            TenLoaiPhep = "Nghỉ việc riêng"
                        },
                        new
                        {
                            MaLoaiPhep = 5,
                            CoLuong = true,
                            MoTa = "Nghỉ thai sản theo quy định",
                            TenLoaiPhep = "Nghỉ thai sản"
                        });
                });

            modelBuilder.Entity("HRM.Domain.Entities.LoaiPhuCap", b =>
                {
                    b.Property<int>("MaPhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuCap"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenPhuCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhuCap");

                    b.ToTable("LoaiPhuCap", (string)null);

                    b.HasData(
                        new
                        {
                            MaPhuCap = 1,
                            MoTa = "Hỗ trợ tiền ăn trưa hàng tháng",
                            SoTien = 730000m,
                            TenPhuCap = "Phụ cấp ăn trưa"
                        },
                        new
                        {
                            MaPhuCap = 2,
                            MoTa = "Hỗ trợ chi phí đi lại",
                            SoTien = 500000m,
                            TenPhuCap = "Phụ cấp xăng xe"
                        },
                        new
                        {
                            MaPhuCap = 3,
                            MoTa = "Hỗ trợ chi phí liên lạc",
                            SoTien = 300000m,
                            TenPhuCap = "Phụ cấp điện thoại"
                        },
                        new
                        {
                            MaPhuCap = 4,
                            MoTa = "Phụ cấp theo vị trí công việc",
                            SoTien = 1000000m,
                            TenPhuCap = "Phụ cấp vị trí"
                        },
                        new
                        {
                            MaPhuCap = 5,
                            MoTa = "Phụ cấp cho vị trí quản lý",
                            SoTien = 2000000m,
                            TenPhuCap = "Phụ cấp trách nhiệm"
                        });
                });

            modelBuilder.Entity("HRM.Domain.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CCCD")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<string>("MaNV")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComputedColumnSql("('NV' + RIGHT('00000' + CAST(MaNhanVien AS VARCHAR(5)), 5))", true);

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<decimal>("MucLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNghiViec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("TaiKhoanMaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrangHonNhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Đang làm việc");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("CCCD")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("HoTen");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("TaiKhoanMaTaiKhoan");

                    b.HasIndex("TrangThai");

                    b.ToTable("NhanVien", (string)null);

                    b.HasData(
                        new
                        {
                            MaNhanVien = 1,
                            CCCD = "000000000001",
                            DiaChi = "Hà Nội",
                            Email = "admin@hrm.com",
                            GioiTinh = "Nam",
                            HoTen = "Quản trị viên",
                            MaChucVu = 1,
                            MaPhongBan = 1,
                            MucLuong = 50000000m,
                            NgayCapNhat = new DateTime(2026, 4, 21, 19, 19, 35, 515, DateTimeKind.Local).AddTicks(8005),
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2026, 4, 21, 19, 19, 35, 515, DateTimeKind.Local).AddTicks(7981),
                            NgayVaoLam = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000001",
                            TrangThai = "Đang làm việc"
                        });
                });

            modelBuilder.Entity("HRM.Domain.Entities.PhanCongDaoTao", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<decimal?>("KetQuaKiemTra")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaDaoTao")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhanHoi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Đã đăng ký");

                    b.Property<decimal>("TyLeThamDu")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaDaoTao", "MaNhanVien")
                        .IsUnique();

                    b.ToTable("PhanCongDaoTao", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongBan"));

                    b.Property<string>("DiaDiemLamViec")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaTruongPhong")
                        .HasColumnType("int");

                    b.Property<string>("MoTaChucNang")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("NganSach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("MaPhongBan");

                    b.HasIndex("MaTruongPhong");

                    b.ToTable("PhongBan", (string)null);

                    b.HasData(
                        new
                        {
                            MaPhongBan = 1,
                            DiaDiemLamViec = "Tầng 10",
                            MoTaChucNang = "Điều hành toàn bộ hoạt động công ty",
                            NgayCapNhat = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(156),
                            NgayTao = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(131),
                            NgayThanhLap = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhongBan = "Ban Giám đốc",
                            TrangThai = "Hoạt động"
                        },
                        new
                        {
                            MaPhongBan = 2,
                            DiaDiemLamViec = "Tầng 5",
                            MoTaChucNang = "Quản lý nhân sự, tuyển dụng, đào tạo",
                            NgayCapNhat = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(181),
                            NgayTao = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(181),
                            NgayThanhLap = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhongBan = "Phòng Nhân sự",
                            TrangThai = "Hoạt động"
                        },
                        new
                        {
                            MaPhongBan = 3,
                            DiaDiemLamViec = "Tầng 5",
                            MoTaChucNang = "Quản lý tài chính, kế toán",
                            NgayCapNhat = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(184),
                            NgayTao = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(183),
                            NgayThanhLap = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhongBan = "Phòng Kế toán",
                            TrangThai = "Hoạt động"
                        },
                        new
                        {
                            MaPhongBan = 4,
                            DiaDiemLamViec = "Tầng 3",
                            MoTaChucNang = "Phát triển kinh doanh, bán hàng",
                            NgayCapNhat = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(186),
                            NgayTao = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(185),
                            NgayThanhLap = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhongBan = "Phòng Kinh doanh",
                            TrangThai = "Hoạt động"
                        },
                        new
                        {
                            MaPhongBan = 5,
                            DiaDiemLamViec = "Tầng 4",
                            MoTaChucNang = "Phát triển sản phẩm, kỹ thuật",
                            NgayCapNhat = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(188),
                            NgayTao = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(187),
                            NgayThanhLap = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhongBan = "Phòng Kỹ thuật",
                            TrangThai = "Hoạt động"
                        },
                        new
                        {
                            MaPhongBan = 6,
                            DiaDiemLamViec = "Tầng 3",
                            MoTaChucNang = "Marketing, truyền thông",
                            NgayCapNhat = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(190),
                            NgayTao = new DateTime(2026, 4, 21, 19, 19, 35, 520, DateTimeKind.Local).AddTicks(190),
                            NgayThanhLap = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhongBan = "Phòng Marketing",
                            TrangThai = "Hoạt động"
                        });
                });

            modelBuilder.Entity("HRM.Domain.Entities.PhongVan", b =>
                {
                    b.Property<int>("MaPhongVan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongVan"));

                    b.Property<string>("CauHoiPhongVan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("DiemDanhGia")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaUngVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPhongVan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiPhongVan")
                        .HasColumnType("int");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đã lên lịch");

                    b.Property<int>("VongPhongVan")
                        .HasColumnType("int");

                    b.HasKey("MaPhongVan");

                    b.HasIndex("MaUngVien");

                    b.HasIndex("NguoiPhongVan");

                    b.ToTable("PhongVan", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.PhuCapNhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaPhuCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNhanVien", "MaPhuCap", "NgayApDung");

                    b.HasIndex("MaPhuCap");

                    b.ToTable("PhuCapNhanVien", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.QuyetDinhTuyenDung", b =>
                {
                    b.Property<int>("MaQuyetDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyetDinh"));

                    b.Property<bool>("DaGuiOfferLetter")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaUngVien")
                        .HasColumnType("int");

                    b.Property<decimal?>("MucLuongDeXuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NgayBatDauLamViec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiQuyetDinh")
                        .HasColumnType("int");

                    b.Property<string>("PhanHoiUngVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaQuyetDinh");

                    b.HasIndex("MaUngVien")
                        .IsUnique();

                    b.HasIndex("NguoiQuyetDinh");

                    b.ToTable("QuyetDinhTuyenDung", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.SoNgayPhep", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("PhepNamCuConLai")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayDaSuDung")
                        .HasColumnType("int");

                    b.Property<int>("TongSoNgayPhep")
                        .HasColumnType("int");

                    b.HasKey("MaNhanVien", "Nam");

                    b.ToTable("SoNgayPhep", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("TaiKhoan", (string)null);

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            MaNhanVien = 1,
                            MatKhauHash = "$2a$11$KWj.ShrxV4ZnlRTKcJZmWODKnW5JlDBA.n3P2pu68ifqc06xQcCve",
                            NgayTao = new DateTime(2026, 4, 21, 19, 19, 35, 478, DateTimeKind.Local).AddTicks(5638),
                            TenDangNhap = "admin",
                            TrangThai = "Hoạt động",
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("HRM.Domain.Entities.TaiLieuNhanVien", b =>
                {
                    b.Property<int>("MaTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiLieu"));

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaTaiLieu");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("TaiLieuNhanVien", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNguoiNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanVienMaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaNguoiNhan");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.ThuongPhat", b =>
                {
                    b.Property<int>("MaThuongPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuongPhat"));

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LoaiChiTiet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiPheDuyet")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chờ duyệt");

                    b.HasKey("MaThuongPhat");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NguoiPheDuyet");

                    b.ToTable("ThuongPhat", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.TinTuyenDung", b =>
                {
                    b.Property<int>("MaTinTuyenDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinTuyenDung"));

                    b.Property<string>("DiadiemLamViec")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("MoTaCongViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MucLuongMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MucLuongMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongCanTuyen")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiHanNhanHoSo")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Đang tuyển");

                    b.Property<string>("ViTriTuyenDung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("YeuCauUngVien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinTuyenDung");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("NguoiTao");

                    b.ToTable("TinTuyenDung", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.UngVien", b =>
                {
                    b.Property<int>("MaUngVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUngVien"));

                    b.Property<string>("BangCap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DuongDanCV")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DuongDanThuXinViec")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KinhNghiem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KyNang")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaTinTuyenDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhanLoai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Chờ xem xét");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Mới nộp");

                    b.HasKey("MaUngVien");

                    b.HasIndex("MaTinTuyenDung");

                    b.ToTable("UngVien", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.XacNhanChinhSach", b =>
                {
                    b.Property<int>("MaXacNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXacNhan"));

                    b.Property<int>("ChinhSachMaChinhSach")
                        .HasColumnType("int");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("MaChinhSach")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienMaNhanVien")
                        .HasColumnType("int");

                    b.HasKey("MaXacNhan");

                    b.HasIndex("ChinhSachMaChinhSach");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("XacNhanChinhSach", (string)null);
                });

            modelBuilder.Entity("HRM.Domain.Entities.BangLuong", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("BangLuongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChamCong", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChinhSach", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiPheDuyetNav")
                        .WithMany()
                        .HasForeignKey("NguoiPheDuyetNavMaNhanVien");

                    b.Navigation("NguoiPheDuyetNav");
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChungChi", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("ChungChis")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.DanhGiaDaoTao", b =>
                {
                    b.HasOne("HRM.Domain.Entities.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaDaoTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.DieuChinhChamCong", b =>
                {
                    b.HasOne("HRM.Domain.Entities.ChamCong", "ChamCong")
                        .WithMany("DieuChinhs")
                        .HasForeignKey("MaChamCong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiDieuChinhNav")
                        .WithMany()
                        .HasForeignKey("NguoiDieuChinh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChamCong");

                    b.Navigation("NguoiDieuChinhNav");
                });

            modelBuilder.Entity("HRM.Domain.Entities.DonNghiPhep", b =>
                {
                    b.HasOne("HRM.Domain.Entities.LoaiNghiPhep", "LoaiNghiPhep")
                        .WithMany("DonNghiPheps")
                        .HasForeignKey("MaLoaiPhep")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("DonNghiPheps")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiPheDuyetNav")
                        .WithMany()
                        .HasForeignKey("NguoiPheDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiNghiPhep");

                    b.Navigation("NguoiPheDuyetNav");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.HieuSuatNhanVien", b =>
                {
                    b.HasOne("HRM.Domain.Entities.KyDanhGia", "KyDanhGia")
                        .WithMany("HieuSuats")
                        .HasForeignKey("MaKyDanhGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KyDanhGia");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.LichSuChinhSach", b =>
                {
                    b.HasOne("HRM.Domain.Entities.ChinhSach", "ChinhSach")
                        .WithMany("LichSus")
                        .HasForeignKey("ChinhSachMaChinhSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiSuaDoiNav")
                        .WithMany()
                        .HasForeignKey("NguoiSuaDoiNavMaNhanVien");

                    b.Navigation("ChinhSach");

                    b.Navigation("NguoiSuaDoiNav");
                });

            modelBuilder.Entity("HRM.Domain.Entities.LichSuDieuChuyen", b =>
                {
                    b.HasOne("HRM.Domain.Entities.ChucVu", "ChucVuCu")
                        .WithMany()
                        .HasForeignKey("MaChucVuCu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.ChucVu", "ChucVuMoi")
                        .WithMany()
                        .HasForeignKey("MaChucVuMoi")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.PhongBan", "PhongBanCu")
                        .WithMany()
                        .HasForeignKey("MaPhongBanCu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.PhongBan", "PhongBanMoi")
                        .WithMany()
                        .HasForeignKey("MaPhongBanMoi")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiThucHienNav")
                        .WithMany()
                        .HasForeignKey("NguoiThucHien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChucVuCu");

                    b.Navigation("ChucVuMoi");

                    b.Navigation("NguoiThucHienNav");

                    b.Navigation("NhanVien");

                    b.Navigation("PhongBanCu");

                    b.Navigation("PhongBanMoi");
                });

            modelBuilder.Entity("HRM.Domain.Entities.NhanVien", b =>
                {
                    b.HasOne("HRM.Domain.Entities.ChucVu", "ChucVu")
                        .WithMany("DanhSachNhanVien")
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.PhongBan", "PhongBan")
                        .WithMany("DanhSachNhanVien")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanMaTaiKhoan");

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HRM.Domain.Entities.PhanCongDaoTao", b =>
                {
                    b.HasOne("HRM.Domain.Entities.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaDaoTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.PhongBan", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "TruongPhong")
                        .WithMany()
                        .HasForeignKey("MaTruongPhong")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TruongPhong");
                });

            modelBuilder.Entity("HRM.Domain.Entities.PhongVan", b =>
                {
                    b.HasOne("HRM.Domain.Entities.UngVien", "UngVien")
                        .WithMany("PhongVans")
                        .HasForeignKey("MaUngVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiPhongVanNav")
                        .WithMany()
                        .HasForeignKey("NguoiPhongVan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiPhongVanNav");

                    b.Navigation("UngVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.PhuCapNhanVien", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.LoaiPhuCap", "LoaiPhuCap")
                        .WithMany("PhuCapNhanViens")
                        .HasForeignKey("MaPhuCap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiPhuCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.QuyetDinhTuyenDung", b =>
                {
                    b.HasOne("HRM.Domain.Entities.UngVien", "UngVien")
                        .WithOne("QuyetDinh")
                        .HasForeignKey("HRM.Domain.Entities.QuyetDinhTuyenDung", "MaUngVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiQuyetDinhNav")
                        .WithMany()
                        .HasForeignKey("NguoiQuyetDinh")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiQuyetDinhNav");

                    b.Navigation("UngVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.SoNgayPhep", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.TaiKhoan", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.TaiLieuNhanVien", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("MaNguoiNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", null)
                        .WithMany("ThongBaos")
                        .HasForeignKey("NhanVienMaNhanVien");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("HRM.Domain.Entities.ThuongPhat", b =>
                {
                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("ThuongPhats")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiPheDuyetNav")
                        .WithMany()
                        .HasForeignKey("NguoiPheDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiPheDuyetNav");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.TinTuyenDung", b =>
                {
                    b.HasOne("HRM.Domain.Entities.PhongBan", "PhongBan")
                        .WithMany("DanhSachTinTuyenDung")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NguoiTaoNav")
                        .WithMany()
                        .HasForeignKey("NguoiTao")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiTaoNav");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("HRM.Domain.Entities.UngVien", b =>
                {
                    b.HasOne("HRM.Domain.Entities.TinTuyenDung", "TinTuyenDung")
                        .WithMany("UngViens")
                        .HasForeignKey("MaTinTuyenDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("HRM.Domain.Entities.XacNhanChinhSach", b =>
                {
                    b.HasOne("HRM.Domain.Entities.ChinhSach", "ChinhSach")
                        .WithMany("XacNhans")
                        .HasForeignKey("ChinhSachMaChinhSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRM.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienMaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChinhSach");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChamCong", b =>
                {
                    b.Navigation("DieuChinhs");
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChinhSach", b =>
                {
                    b.Navigation("LichSus");

                    b.Navigation("XacNhans");
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChucVu", b =>
                {
                    b.Navigation("DanhSachNhanVien");
                });

            modelBuilder.Entity("HRM.Domain.Entities.ChuongTrinhDaoTao", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("HRM.Domain.Entities.KyDanhGia", b =>
                {
                    b.Navigation("HieuSuats");
                });

            modelBuilder.Entity("HRM.Domain.Entities.LoaiNghiPhep", b =>
                {
                    b.Navigation("DonNghiPheps");
                });

            modelBuilder.Entity("HRM.Domain.Entities.LoaiPhuCap", b =>
                {
                    b.Navigation("PhuCapNhanViens");
                });

            modelBuilder.Entity("HRM.Domain.Entities.NhanVien", b =>
                {
                    b.Navigation("BangLuongs");

                    b.Navigation("ChamCongs");

                    b.Navigation("ChungChis");

                    b.Navigation("DonNghiPheps");

                    b.Navigation("TaiLieus");

                    b.Navigation("ThongBaos");

                    b.Navigation("ThuongPhats");
                });

            modelBuilder.Entity("HRM.Domain.Entities.PhongBan", b =>
                {
                    b.Navigation("DanhSachNhanVien");

                    b.Navigation("DanhSachTinTuyenDung");
                });

            modelBuilder.Entity("HRM.Domain.Entities.TinTuyenDung", b =>
                {
                    b.Navigation("UngViens");
                });

            modelBuilder.Entity("HRM.Domain.Entities.UngVien", b =>
                {
                    b.Navigation("PhongVans");

                    b.Navigation("QuyetDinh");
                });
#pragma warning restore 612, 618
        }
    }
}
